# Site settings
title: ICM Quizzes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ICM Quizzes
<<<<<<< HEAD
baseurl: "/ICM-Quizzes" # the subpath of your site, e.g. /blog/
# url: "http://ITPNYU.github.io" # the base hostname & protocol for your site
url: "http://yining1023.github.io"
=======
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ITPNYU.github.io" # the base hostname & protocol for your site
>>>>>>> upstream/gh-pages
markdown: kramdown
